gherkin-doctor:
  feature-location: ${SOURCE_FEATURE_FILES:features/LintTest.feature}
  rules:
    indentation:
      active: true
      mappings:
        feature: 1
        background: 3
        scenario: 3
        step: 5

spring:
  main:
    lazy-initialization: true
  shell:
    interactive:
      enabled: true
