gherkin-doctor:
  feature-location: ${SOURCE_FEATURE_FILES:features/LintTest.feature}
  rules:
    indentation:
      active: true
      mappings:
        feature: 0
        background: 2
        scenario: 2
        step: 4

spring:
  main:
    lazy-initialization: true
  shell:
    interactive:
      enabled: true
